# примеры API-запросов

@baseUrl = http://localhost:8000/api
@token1 = 7b61f8b62f5a99fb1836ff3ac62a381eb343bd0d
@token2 = e56eb8e7ae50afcbe9c2b9b4077debaca15eed1b


# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token {{ token1 }}

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token {{ token2 }}

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2024-09-30
Content-Type: application/json

###

DELETE {{baseUrl}}/advertisements/6/
Content-Type: application/json
Authorization: Token {{ token2}}

###