# Generated by Django 5.1 on 2024-09-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_measurement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='image',
        ),
    ]
